name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        cd server
        python -m pip install --upgrade pip
        docker run --rm \
        --volume=$(pwd):/lambda-build \
        -w=/lambda-build \
        lambci/lambda:build-python3.8 \
        pip install -r requirements.txt --target .dependencies


  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
    - uses: actions/checkout@v2

    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2

    - name: Package Lambda function
      run: |
        # Package your Lambda function, e.g., zip for Python
        zip -r function.zip .

    - name: Deploy to AWS Lambda
      run: |
        # Deploy the function to AWS Lambda
        aws lambda update-function-code --function-name ArcticDesignsLambda --zip-file fileb://function.zip
